"""empty message

Revision ID: 5661fa04666f
Revises: 
Create Date: 2022-06-13 19:13:34.815174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5661fa04666f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('buildings', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'lon')
    op.drop_column('buildings', 'lat')
    # ### end Alembic commands ###
